recomendacion_project/recomendacion_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recomendaciones.urls')),
]

recomendacion_project/recomendaciones/urls.py
from django.urls import path

from . import views

app_name = 'recomendaciones'  # Namespace
urlpatterns = [
    # the 'name' value as called by the {% url %} template tag
    path('', views.index, name='index'),
    path('enviadas/', views.RecomendacionesListView.as_view(), name='enviadas'),
    path('api/recomendaciones/', views.Recomendaciones.as_view(), name='lista'),
]

recomendacion_project/recomendaciones/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Recomendacion(models.Model):
    titulo = models.CharField('Título', max_length=80)
    contenido = models.TextField('Contenido')
    pub_date = models.DateTimeField('Date Published', default=timezone.now)
    seleccionado = models.BooleanField(default=False)

    def __str__(self):
        return ' - '.join([self.titulo, str(self.pub_date)])

    def as_json_dict(self):
        json_dict = {
            'titulo': self.titulo,
            'contenido': self.contenido,
            'pub_date': str(self.pub_date),
            'seleccionado': self.seleccionado
        }
        return json_dict

recomendacion_project/recomendaciones/views.py
import json

from django.shortcuts import render, reverse, get_list_or_404
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.views import generic

from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from .app_settings import app_settings
from . import models

# Create your views here.

def index(request):
    if request.method == 'GET':
        # Setup dark theme
        if not request.session.get('dark_theme'):
            request.session['dark_theme'] = app_settings.SESSION_DEFAULT_THEME_ISDARK
        if 'changetheme' in request.GET.keys():
            request.session['dark_theme'] = not request.session.get('dark_theme')
            return HttpResponseRedirect(reverse('recomendaciones:index'))
        ##

    if request.method == 'POST':
        print(request.POST)
        new_rec = models.Recomendacion(
            titulo=request.POST.get('titulo'),
            contenido=request.POST.get('contenido_receta'),
            pub_date=timezone.now()
            )   
        new_rec.save()

    return render(request, 'recomendaciones/index.html')


class RecomendacionesListView(generic.ListView):
    model = models.Recomendacion
    template_name = 'recomendaciones/enviadas.html'


# API
class Recomendaciones(APIView):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

    def get(self, request, format=None):
        lista_rec = get_list_or_404(models.Recomendacion.objects.all())
        lista_rec = [x.as_json_dict() for x in lista_rec]
        print(lista_rec)

        content = {
            'recomendaciones': json.dumps(lista_rec)
        }
        return Response(content)

recomendacion_project/recomendaciones/templates/recomendaciones/enviadas.html
{% extends "recomendaciones/layouts/base.html" %}


{% block page_content %}
    {% if object_list %}
        <ul>
        {% for recomendacion in object_list %}
            <li>{{ recomendacion.titulo }} - {{recomendacion.contenido}}</li>
            <hr>
        {% endfor %}
        </ul>
    {% else %}
        <p>No hay recomendaciones enviadas.</p>
    {% endif %}
{% endblock %}

recomendacion_project/recomendaciones/templates/recomendaciones/index.html
{% extends "recomendaciones/layouts/base.html" %}

{% block page_head %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static "css\trix.css" %}">
    <script type="text/javascript" src="{% static "js\trix.js" %}"></script>
{% endblock %}

{% block page_content %}
    <div class="jumbotron">
        <h1 class="display-4">Recomendaciones</h1>
        <p class="lead">Envia tus recomendaciones:</p>
        <hr class="my-2 p-2">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <form action="" method="post">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            <label for="titulo">Titulo:</label>
                            <input type="text" name="titulo" id="titulo" class="form-control" placeholder="Titulo de la receta" aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="contenido">Contenido:</label>
                            <input id="contenido_receta" type="hidden" name="contenido_receta">
                            <trix-editor id="contenido" input="contenido_receta"></trix-editor>
                        </div>
                        <button type="submit" class="btn btn-success">Enviar</button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

recomendacion_project/recomendaciones/templates/recomendaciones/layouts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="App Recomendaciones">
    <meta name="author" content="plabin">

    {% if custom_title %}
        <title>Recomendaciones - {{ titulo }}</title>
	{% else %}
	    <title>Recomendaciones </title>
    {% endif %}
    <!-- Static Files -->
    {% load static %}
    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    {% if request.session.dark_theme%}
        <link href="{% static "css\bootstrap.min.css" %}" rel="stylesheet" type="text/css">
    {% else %}
        <link href="{% static "css\material.bootstrap.min.css" %}" rel="stylesheet" type="text/css">
    {% endif %}
    <!-- \Bootstrap -->

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <!-- \Font Awesome -->

    <!-- Load more files here: -->
    {% block page_head %}
    {% endblock %}
    <!-- \-->
    <!--\Static Files-->

</head>

<style>
    body {
        /*margin-top: 80px;*/
        word-wrap: break-word;
        min-height: 100vh;
    }
</style>

<body class="d-flex flex-column">
	<!-- navbar -->
    <nav class="navbar navbar-expand-xl navbar-dark bg-primary sticky-top mb-3">
        <div class="container">
            <a class="navbar-brand" href="{% url 'recomendaciones:index' %}"><i class="fas fa-tasks"></i> Recomendaciones</a>
            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#topNavBar" aria-controls="topNavBar" aria-expanded="false" aria-label="Toggle navigation" style="">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="topNavBar" style="">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "recomendaciones:enviadas" %}">Enviadas</a>
                    </li>
                </ul>
            
                <hr>

                <ul class="navbar-nav ml-xl-3 ml-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'recomendaciones:index'%}?changetheme"><i class="fas fa-palette"></i> Change Theme</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}"><i class="fa fa-sign-in-alt"></i> Admin</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Content -->
    <main class="container" role="main" style="flex: 1;">
        {#{% include 'components/_messages.html' %}#}
        {% block page_content %}
        {% endblock %}
    </main>

    <!-- /.container -->
     <footer class="footer mt-5">
        <div class="container">
            <div class="row">
                <div class="col-6 float-left">
                    <p>Patricio Labin<br>plabin@outlook.cl</p>
                </div>
                <div class="col-6 float-right">
                    <p class="text-right">
                        <a href="https://gitlab.com/plabin/recomendaciones_app">Fork Me on Gitlab! <i class="fab fa-gitlab"></i></a><br>
                        <a href="http://getbootstrap.com/">Created with Bootstrap 4</a><br>
                        <a href="https://bootswatch.com/darkly/">Darkly Theme</a>
                    </p>
                </div>
            </div>
        </div>
     </footer>

    {% block page_script %}
    {% endblock %}
</body>
</html>